name: Dreamscape Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  ORG: DREAMSCAPE-AI
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone frontend & services (via PAT)
        env:
          TOKEN: ${{ secrets.CI_CLONE_TOKEN }}
        run: |
          set -euo pipefail
          for repo in dreamscape-frontend dreamscape-services; do
            url="https://x-access-token:${TOKEN}@github.com/${{ env.ORG }}/${repo}.git"
            if git ls-remote --heads "$url" "${{ env.BRANCH_NAME }}" | grep -q "${{ env.BRANCH_NAME }}"; then
              echo "Cloning ${repo} @ ${{ env.BRANCH_NAME }}"
              git clone --depth 1 --branch "${{ env.BRANCH_NAME }}" "$url" "$repo"
            else
              echo "Branch ${{ env.BRANCH_NAME }} not found in ${repo}, fallback to default"
              git clone --depth 1 "$url" "$repo"
            fi
          done

      # Cache npm seulement si un lockfile existe (racine ou clones)
      - name: Setup Node with cache (if lockfile exists)
        if: ${{ hashFiles('package-lock.json','dreamscape-frontend/package-lock.json','dreamscape-services/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            package-lock.json
            dreamscape-frontend/package-lock.json
            dreamscape-services/package-lock.json

      - name: Setup Node (no cache)
        if: ${{ hashFiles('package-lock.json','dreamscape-frontend/package-lock.json','dreamscape-services/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # (facultatif) si ton repo de tests a un package.json
      - name: Install test deps (root)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci

      - name: Build tests (root, if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm run build --if-present

      - name: Install & build frontend (if Node)
        run: |
          if [ -f dreamscape-frontend/package.json ]; then
            (cd dreamscape-frontend && npm ci && npm run build --if-present)
          else
            echo "No frontend package.json → skip"
          fi

      - name: Install & build services (if Node)
        run: |
          if [ -f dreamscape-services/package.json ]; then
            (cd dreamscape-services && npm ci && npm run build --if-present)
          else
            echo "No services package.json → skip"
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Lint tests repo (root, if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          npm ci
          npm run lint --if-present

  unit-tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone frontend & services (via PAT)
        env:
          TOKEN: ${{ secrets.CI_CLONE_TOKEN }}
        run: |
          set -euo pipefail
          for repo in dreamscape-frontend dreamscape-services; do
            url="https://x-access-token:${TOKEN}@github.com/${{ env.ORG }}/${repo}.git"
            git clone --depth 1 "$url" "$repo" || true
          done
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps (root, if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci
      - name: Run unit tests
        run: |
          if [ -z "$(find . -name '*.test.js')" ]; then
            echo "No tests found. Skipping."
            exit 0
          fi
          npm run test:unit || echo "No test:unit script → skipping"

  integration-tests:
    needs: [build]
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5
        ports:
          - "27017:27017"
      redis:
        image: redis:7
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v4
      - name: Clone frontend & services (via PAT)
        env:
          TOKEN: ${{ secrets.CI_CLONE_TOKEN }}
        run: |
          set -euo pipefail
          for repo in dreamscape-frontend dreamscape-services; do
            url="https://x-access-token:${TOKEN}@github.com/${{ env.ORG }}/${repo}.git"
            git clone --depth 1 "$url" "$repo" || true
          done
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps (root, if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci
      - name: Run integration tests
        env:
          TEST_DATABASE_URL: mongodb://localhost:27017/dreamscape_test
          REDIS_URL: redis://localhost:6379
        run: |
          if [ -z "$(find . -name '*.test.integration.js')" ]; then
            echo "No integration tests found. Skipping."
            exit 0
          fi
          npm run test:integration || echo "No test:integration script → skipping"

  e2e-tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone frontend & services (via PAT)
        env:
          TOKEN: ${{ secrets.CI_CLONE_TOKEN }}
        run: |
          set -euo pipefail
          for repo in dreamscape-frontend dreamscape-services; do
            url="https://x-access-token:${TOKEN}@github.com/${{ env.ORG }}/${repo}.git"
            git clone --depth 1 "$url" "$repo" || true
          done
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps (root, if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci
      - name: Start services
        run: |
          if [ ! -f docker-compose.test.yml ]; then
            echo "docker-compose.test.yml missing → skip E2E."
            exit 0
          fi
          docker compose -f docker-compose.test.yml up -d
          sleep 30
      - name: Run E2E tests
        run: |
          if [ -z "$(find . -name '*.test.e2e.js')" ]; then
            echo "No E2E tests found. Skipping."
            exit 0
          fi
          npm run test:e2e || echo "No test:e2e script → skipping"
      - name: Stop services
        if: always()
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker compose -f docker-compose.test.yml down
          fi

  test:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, e2e-tests]
    steps:
      - run: echo "All tests green ✅"
